src/ContosoUniversity.Website/Models/Instructor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ContosoUniversity.Models
{
    public class Instructor : Person
    {
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(Name = "Hire Date")]
        public DateTime HireDate { get; set; }

        public virtual ICollection<InstructorCourse> Courses { get; set; }
        public virtual OfficeAssignment OfficeAssignment { get; set; }
    }
}

src/ContosoUniversity.Website/Controllers/InstructorController.cs
using ContosoUniversity.DAL;
using ContosoUniversity.Models;
using ContosoUniversity.ViewModels;
using Microsoft.AspNet.Mvc;
using Microsoft.Data.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ContosoUniversity.Website.Controllers
{
    public class InstructorController : Controller
    {
        private readonly ISchoolContext _db;

        public InstructorController(ISchoolContext db)
        {
            _db = db;
        }

        public async Task<ActionResult> Index(int? id, int? courseID)
        {
            var viewModel = new InstructorIndexData();

            var instructors = await _db.Instructors
                .Include(i => i.OfficeAssignment)
                .Include(i => i.Courses)
                    .ThenInclude(c => c.Course)
                        .ThenInclude(c => c.Department)
                .Include(i => i.Courses)
                    .ThenInclude(c => c.Course)
                        .ThenInclude(c => c.Enrollments)
                            .ThenInclude(e => e.Student)
                .OrderBy(i => i.LastName)
                .ToListAsync();

            viewModel.Instructors = instructors;

            if (id != null)
            {
                ViewBag.InstructorID = id.Value;
                viewModel.Courses = viewModel.Instructors.Where(
                    i => i.ID == id.Value).Single().Courses.Select(c => c.Course);
            }

            if (courseID != null)
            {
                ViewBag.CourseID = courseID.Value;
                viewModel.Enrollments = viewModel.Courses
                    .Where(x => x.CourseID == courseID)
                    .Single().Enrollments;
            }

            return View(viewModel);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
                return HttpBadRequest();

            Instructor instructor = _db.Instructors
                .Include(i => i.OfficeAssignment)
                .FirstOrDefault(i => i.ID == id);

            if (instructor == null)
                return HttpNotFound();

            return View(instructor);
        }

        public ActionResult Create()
        {
            var instructor = new Instructor();
            instructor.Courses = new List<InstructorCourse>();
            PopulateAssignedCourseData(instructor);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("LastName", "FirstMidName", "HireDate", "OfficeAssignment")] Instructor instructor, string[] selectedCourses)
        {
            if (ModelState.IsValid)
            {
                if (selectedCourses != null)
                {
                    instructor.Courses = new List<InstructorCourse>();
                    foreach (var course in selectedCourses)
                    {
                        var courseToAdd = _db.Courses.First(c => c.CourseID == int.Parse(course));
                        var instructorCourse = new InstructorCourse { Course = courseToAdd, };
                        instructor.Courses.Add(instructorCourse);
                        _db.Entry(instructorCourse).State = Microsoft.Data.Entity.EntityState.Added;
                    }
                }
                _db.Entry(instructor.OfficeAssignment).State = Microsoft.Data.Entity.EntityState.Added;
                _db.Instructors.Add(instructor);
                await _db.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            PopulateAssignedCourseData(instructor);
            return View(instructor);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
                return HttpBadRequest();

            Instructor instructor = _db.Instructors
                .Include(i => i.OfficeAssignment)
                .Include(i => i.Courses)
                    .ThenInclude(c => c.Course)
                .Where(i => i.ID == id)
                .Single();

            PopulateAssignedCourseData(instructor);

            if (instructor == null)
                return HttpNotFound();

            return View(instructor);
        }

        private void PopulateAssignedCourseData(Instructor instructor)
        {
            var allCourses = _db.Courses;
            var instructorCourses = new HashSet<int>(instructor.Courses.Select(c => c.Course.CourseID));
            var viewModel = new List<AssignedCourseData>();
            foreach (var course in allCourses)
            {
                viewModel.Add(new AssignedCourseData
                {
                    CourseID = course.CourseID,
                    Title = course.Title,
                    Assigned = instructorCourses.Contains(course.CourseID)
                });
            }
            ViewBag.Courses = viewModel;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind("ID", "LastName", "FirstMidName", "HireDate", "OfficeAssignment")] Instructor instructor, string[] selectedCourses)
        {
            var instructorToUpdate = await _db.Instructors
               .Include(i => i.OfficeAssignment)
               .Include(i => i.Courses)
                    .ThenInclude(c => c.Course)
               .SingleOrDefaultAsync(i => i.ID == instructor.ID);

            if (instructorToUpdate == null)
                return HttpBadRequest();

            if (await TryUpdateModelAsync(instructorToUpdate))
            {
                try
                {
                    if (String.IsNullOrWhiteSpace(instructor.OfficeAssignment.Location))
                        instructorToUpdate.OfficeAssignment = null;

                    UpdateInstructorCourses(selectedCourses, instructorToUpdate);

                    await _db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }
            PopulateAssignedCourseData(instructorToUpdate);
            return View(instructorToUpdate);
        }

        private void UpdateInstructorCourses(string[] selectedCourses, Instructor instructorToUpdate)
        {
            if (selectedCourses == null)
            {
                instructorToUpdate.Courses = new List<InstructorCourse>();
                return;
            }

            var selectedCoursesHS = new HashSet<string>(selectedCourses);
            var instructorCourses = new HashSet<int>(instructorToUpdate.Courses.Select(c => c.Course.CourseID));

            foreach (var course in _db.Courses)
            {
                if (selectedCoursesHS.Contains(course.CourseID.ToString()))
                {
                    if (!instructorCourses.Contains(course.CourseID))
                    {
                        instructorToUpdate.Courses.Add(new InstructorCourse
                        {
                            Course = course,
                        });
                    }
                }
                else
                {
                    if (instructorCourses.Contains(course.CourseID))
                    {
                        instructorToUpdate.Courses.Remove(
                            instructorToUpdate.Courses.Where(c => c.CourseID == course.CourseID).Single());
                    }
                }
            }
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
                return HttpBadRequest();

            Instructor instructor = _db.Instructors
                .Include(i => i.OfficeAssignment)
                .First(i => i.ID == id);
            if (instructor == null)
                return HttpNotFound();

            return View(instructor);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Instructor instructor = _db.Instructors
              .Include(i => i.OfficeAssignment)
                .Include(i => i.Courses)
                    .ThenInclude(c => c.Course)
                        .ThenInclude(c => c.Department)

              .Where(i => i.ID == id)
              .Single();

            _db.Instructors.Remove(instructor);

            var departments = _db.Departments.Where(d => d.InstructorID == id);
            foreach (var department in departments)
                department.InstructorID = 0;

            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/ContosoUniversity.Website/Views/Instructor/Create.cshtml
@model ContosoUniversity.Models.Instructor

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<form asp-controller="Instructor" asp-action="Create" method="post" class="form-horizontal" role="form">

    <div class="form-horizontal">
        <h4>Instructor</h4>
        <hr />
        <div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="LastName" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="FirstMidName" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <input asp-for="FirstMidName" class="form-control" />
                <span asp-validation-for="FirstMidName" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="HireDate" class="control-label col-md-2"></label>
            <div class="col-md-3">
                <div class="input-group input-append date picker" data-date-format="yyyy-mm-dd">
                    <input asp-for="HireDate" asp-format="{0:yyyy-MM-dd}" class="form-control" />
                    <span class="input-group-btn">
                        <span class="btn btn-default"><i class="glyphicon glyphicon-calendar"></i></span>
                    </span>
                </div>
                <span asp-validation-for="HireDate" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="OfficeAssignment.Location" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <input asp-for="OfficeAssignment.Location" class="form-control" />
                <span asp-validation-for="OfficeAssignment.Location" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <table>
                    @{
                        List<ContosoUniversity.ViewModels.AssignedCourseData> courses = ViewBag.Courses;
                        foreach (var course in courses)
                        {
                            <tr>
                                <td>
                                    <div class="checkbox-inline">
                                        <label>
                                            <input type="checkbox" name="selectedCourses" value="@course.CourseID" checked="@course.Assigned">
                                            @course.ToString()
                                        </label>
                                    </div>
                                </td>
                            </tr>
                        }
                    }
                </table>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-controller="Instructor" asp-action="Index">Back to List</a>
</div>

@section Scripts
{
    <script src="~/lib/jquery-validation/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

    <link href="~/lib/bootstrap-datepicker/dist/css/bootstrap-datepicker3.css" rel="stylesheet" />
    <script src="~/lib/bootstrap-datepicker/dist/js/bootstrap-datepicker.js"></script>

    <script>
        $('.picker').datepicker(
            {
                autoclose: true,
                format: 'yyyy-mm-dd',
                todayBtn: true
            });
    </script>
}

src/ContosoUniversity.Website/Views/Instructor/Delete.cshtml
@model ContosoUniversity.Models.Instructor

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Instructor</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt><label asp-for="OfficeAssignment.Location"></label></dt>
        <dd>@Model.OfficeAssignment.Location</dd>

        <dt><label asp-for="LastName"></label></dt>
        <dd>@Model.LastName</dd>

        <dt><label asp-for="FirstMidName"></label></dt>
        <dd>@Model.FirstMidName</dd>

        <dt><label asp-for="HireDate"></label></dt>
        <dd><display asp-for="HireDate" /></dd>
    </dl>

    <form asp-controller="Instructor" asp-action="Delete" method="post" role="form">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a asp-controller="Instructor" asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

src/ContosoUniversity.Website/Views/Instructor/Details.cshtml
@model ContosoUniversity.Models.Instructor

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Instructor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt><label asp-for="OfficeAssignment.Location"></label></dt>
        <dd>@Model.OfficeAssignment.Location</dd>

        <dt><label asp-for="LastName"></label></dt>
        <dd>@Model.LastName</dd>

        <dt><label asp-for="FirstMidName"></label></dt>
        <dd>@Model.FirstMidName</dd>

        <dt><label asp-for="HireDate"></label></dt>
        <dd><display asp-for="HireDate" /></dd>
    </dl>
</div>
<p>
    <a asp-controller="Instructor" asp-action="Edit" asp-route-id=@Model.ID>Edit</a> |
    <a asp-controller="Instructor" asp-action="Index">Back to List</a>
</p>

src/ContosoUniversity.Website/Views/Instructor/Edit.cshtml
@model ContosoUniversity.Models.Instructor

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<form asp-controller="Instructor" asp-action="Edit" method="post" class="form-horizontal" role="form">
    <h4>Instructor</h4>
    <hr />
    <div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
    <input asp-for="ID" type="hidden" />

    <div class="form-group">
        <label asp-for="LastName" class="control-label col-md-2"></label>
        <div class="col-md-10">
            <input asp-for="LastName" class="form-control" />
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="FirstMidName" class="control-label col-md-2"></label>
        <div class="col-md-10">
            <input asp-for="FirstMidName" class="form-control" />
            <span asp-validation-for="FirstMidName" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="HireDate" class="control-label col-md-2"></label>
        <div class="col-md-3">
            <div class="input-group input-append date picker" data-date-format="yyyy-mm-dd">
                <input asp-for="HireDate" asp-format="{0:yyyy-MM-dd}" class="form-control" />
                <span class="input-group-btn">
                    <span class="btn btn-default"><i class="glyphicon glyphicon-calendar"></i></span>
                </span>
            </div>
            <span asp-validation-for="HireDate" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="OfficeAssignment.Location" class="control-label col-md-2"></label>
        <div class="col-md-10">
            <input asp-for="OfficeAssignment.Location" class="form-control" />
            <span asp-validation-for="OfficeAssignment.Location" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <table>
                @{
                    List<ContosoUniversity.ViewModels.AssignedCourseData> courses = ViewBag.Courses;

                    foreach (var course in courses)
                    {
                        <tr>
                            <td>
                                <div class="checkbox-inline">
                                    <label>
                                        <input type="checkbox" name="selectedCourses" value="@course.CourseID" checked="@course.Assigned">
                                        @course.CourseID - @course.Title
                                    </label>
                                </div>
                            </td>
                        </tr>
                    }
                }
            </table>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-success" />
        </div>
    </div>
</form>

<div>
    <a asp-controller="Instructor" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="~/lib/jquery-validation/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

    <link href="~/lib/bootstrap-datepicker/dist/css/bootstrap-datepicker3.css" rel="stylesheet" />
    <script src="~/lib/bootstrap-datepicker/dist/js/bootstrap-datepicker.js"></script>

    <script>
        $('.picker').datepicker(
            {
                autoclose: true,
                format: 'yyyy-mm-dd',
                todayBtn: true
            });
    </script>
}

src/ContosoUniversity.Website/Views/Instructor/Index.cshtml
@model ContosoUniversity.ViewModels.InstructorIndexData

@{
    ViewBag.Title = "Instructors";
}

<h2>Instructors</h2>

<p>
    <a asp-controller="Instructor" asp-action="Create">Create New</a>
</p>

<table class="table">
    <tr>
        <th>Last Name</th>
        <th>First Name</th>
        <th>Hire Date</th>
        <th>Office</th>
        <th>Courses</th>
        <th></th>
    </tr>

    @foreach (var item in Model.Instructors)
    {
        string selectedRow = "";
        if (item.ID == ViewBag.InstructorID)
        {
            selectedRow = "success";
        }
        <tr class="@selectedRow">
            <td>
                <display asp-for="@item.LastName" />
            </td>
            <td>
                <display asp-for="@item.FirstMidName" />
            </td>
            <td>
                <display asp-for="@item.HireDate" />
            </td>
            <td>
                <display asp-for="@item.OfficeAssignment.Location" />
            </td>
            <td>
                @{
                    foreach (var course in item.Courses)
                    {
                        <a asp-action="details" asp-controller="course" asp-route-id="@course.CourseID"><display asp-for="@course.CourseID" /></a>
                        <display asp-for="@course.Course.Title" />
                        <br />
                    }
                }
            </td>

            <td>
                <a asp-controller="Instructor" asp-action="Index" asp-route-id=@item.ID>Select</a> |
                <a asp-controller="Instructor" asp-action="Edit" asp-route-id=@item.ID>Edit</a> |
                <a asp-controller="Instructor" asp-action="Details" asp-route-id=@item.ID>Details</a> |
                <a asp-controller="Instructor" asp-action="Delete" asp-route-id=@item.ID>Delete</a>
            </td>
        </tr>
                    }

</table>

@if (Model.Courses != null)
{
    <h3>Courses Taught by Selected Instructor</h3>
    <table class="table">
        <tr>
            <th></th>
            <th>Number</th>
            <th>Title</th>
            <th>Department</th>
        </tr>

        @foreach (var item in Model.Courses)
        {
            string selectedRow = "";
            if (item.CourseID == ViewBag.CourseID)
            {
                selectedRow = "success";
            }
            <tr class="@selectedRow">
                <td>
                    <a asp-controller="Instructor" asp-action="Index" asp-route-courseid=@item.CourseID>Select</a>
                </td>
                <td>
                    <a asp-action="details" asp-controller="course" asp-route-id="@item.CourseID"><display asp-for="@item.CourseID" /></a>
                </td>
                <td>
                    <display asp-for="@item.Title" />
                </td>
                <td>
                    <display asp-for="@item.Department.Name" />
                </td>
            </tr>
        }

    </table>
}

@if (Model.Enrollments != null)
{
    <h3>
        Students Enrolled in Selected Course
    </h3>
    <table class="table">
        <tr>
            <th>Name</th>
            <th>Grade</th>
        </tr>
        @foreach (var item in Model.Enrollments)
        {
            <tr>
                <td>
                    <a asp-action="details" asp-controller="student" asp-route-id="@item.Student.ID"><display asp-for="@item.Student.FullName" /></a>
                </td>
                <td>
                    <display asp-for="@item.Grade" />
                </td>
            </tr>
        }
    </table>
}