src/ContosoUniversity.Website/Controllers/CourseController.cs
using ContosoUniversity.DAL;
using ContosoUniversity.Models;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace ContosoUniversity.Website.Controllers
{
    public class CourseController : Controller
    {
        private readonly ISchoolContext _db;

        public CourseController(ISchoolContext db)
        {
            _db = db;
        }

        public ActionResult Index(int? SelectedDepartment)
        {
            var departments = _db.Departments.OrderBy(q => q.Name).ToList();
            PopulateDepartmentsDropDownList(SelectedDepartment);
            int departmentID = SelectedDepartment.GetValueOrDefault();

            IQueryable<Course> courses = _db.Courses
                .Where(c => !SelectedDepartment.HasValue || c.DepartmentID == departmentID)
                .OrderBy(d => d.CourseID)
                .Include(d => d.Department);
            var sql = courses.ToString();
            return View(courses.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
                return HttpBadRequest();

            Course course = _db.Courses
                .Include(d => d.Department)
                .FirstOrDefault(c => c.CourseID == id);
            if (course == null)
                return HttpNotFound();

            return View(course);
        }

        public ActionResult Create()
        {
            PopulateDepartmentsDropDownList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("CourseID", "Title", "Credits", "DepartmentID")]Course course)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _db.Courses.Add(course);
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
            }
            PopulateDepartmentsDropDownList(course.DepartmentID);
            return View(course);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
                return HttpBadRequest();

            Course course = _db.Courses.FirstOrDefault(c => c.CourseID == id);
            if (course == null)
                return HttpNotFound();

            PopulateDepartmentsDropDownList(course.DepartmentID);
            return View(course);
        }

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditPost(int? id)
        {
            if (id == null)
                return HttpBadRequest();

            var courseToUpdate = _db.Courses.First(c => c.CourseID == id);
            if (await TryUpdateModelAsync(courseToUpdate))
            {
                try
                {
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }
            PopulateDepartmentsDropDownList(courseToUpdate.DepartmentID);
            return View(courseToUpdate);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
                return HttpBadRequest();

            Course course = _db.Courses
                .Include(d => d.Department)
                .FirstOrDefault(c => c.CourseID == id);

            if (course == null)
                return HttpNotFound();

            return View(course);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Course course = _db.Courses
                .Include(i => i.Instructors)
                .Include(e => e.Enrollments)
                .First(c => c.CourseID == id);

            foreach (var instructor in course.Instructors)
                _db.InstructorCourses.Remove(instructor);
            foreach (var enrollment in course.Enrollments)
                _db.Enrollments.Remove(enrollment);

            _db.Courses.Remove(course);

            _db.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult UpdateCourseCredits()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UpdateCourseCredits(int? multiplier)
        {
            if (multiplier != null)
            {
                //TODO: Implement equivalent
                //ViewBag.RowsAffected = _db.Database.ExecuteSqlCommand("UPDATE Course SET Credits = Credits * {0}", multiplier);
            }
            return View();
        }

        private void PopulateDepartmentsDropDownList(object selectedDepartment = null)
        {
            var departmentsQuery = from d in _db.Departments
                                   orderby d.Name
                                   select d;
            ViewBag.DepartmentID = new SelectList(departmentsQuery, "DepartmentID", "Name", selectedDepartment);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/ContosoUniversity.Website/Controllers/StudentController.cs
using ContosoUniversity.DAL;
using ContosoUniversity.Models;
using ContosoUniversity.ViewModels;
using Microsoft.AspNet.Mvc;
using Microsoft.Data.Entity;
using Microsoft.Extensions.OptionsModel;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace ContosoUniversity.Website.Controllers
{
    public class StudentController : Controller
    {
        private readonly ISchoolContext _db;
        private IOptions<AppSettings> _settings { get; set; }

        public StudentController(ISchoolContext db, IOptions<AppSettings> settings)
        {
            _db = db;
            _settings = settings;
        }

        public ActionResult Index(string sortOrder, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            ViewBag.SearchString = searchString;

            var students = from s in _db.Students select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                students = students
                    .Where(s => 
                    s.LastName.Contains(searchString, StringComparison.CurrentCultureIgnoreCase) ||
                    s.FirstMidName.Contains(searchString, StringComparison.CurrentCultureIgnoreCase));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    students = students.OrderByDescending(s => s.LastName);
                    break;
                case "Date":
                    students = students.OrderBy(s => s.EnrollmentDate);
                    break;
                case "date_desc":
                    students = students.OrderByDescending(s => s.EnrollmentDate);
                    break;
                default:
                    students = students.OrderBy(s => s.LastName);
                    break;
            }

            var index = page ?? 1;
            var total = students.Count();            
            var size = _settings.Value.PageSize;

            var model = students
                .Skip((index-1) * size)
                .Take(size)
                .ToList();

            if (Request.IsAjaxRequest())
                return PartialView("_Students", new PagedList<Student>(index, size, total, model));
            else
                return View(new PagedList<Student>(index, size, total, model));
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
                return HttpBadRequest();

            Student student = _db.Students
                .Include(s => s.Enrollments)
                    .ThenInclude(e => e.Course)
                .FirstOrDefault(s => s.ID == id);

            if (student == null)
                return HttpNotFound();

            return View(student);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("LastName", "FirstMidName", "EnrollmentDate")] Student student)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _db.Students.Add(student);
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }
            return View(student);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
                return HttpBadRequest();

            Student student = _db.Students.FirstOrDefault(s => s.ID == id);
            if (student == null)
            {
                return HttpNotFound();
            }
            return View(student);
        }

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditPost(int? id)
        {
            if (id == null)
                return HttpBadRequest();

            var studentToUpdate = _db.Students.FirstOrDefault(s => s.ID == id);
            if (await TryUpdateModelAsync(studentToUpdate))
            {
                try
                {
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists, see your system administrator.");
                }
            }
            return View(studentToUpdate);
        }

        public ActionResult Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
                return HttpBadRequest();

            if (saveChangesError.GetValueOrDefault())
                ViewBag.ErrorMessage = "Delete failed. Try again, and if the problem persists see your system administrator.";

            Student student = _db.Students.FirstOrDefault(s => s.ID == id);
            if (student == null)
                return HttpNotFound();

            return View(student);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            try
            {
                Student student = _db.Students.First(s => s.ID == id);
                _db.Students.Remove(student);
                _db.SaveChanges();
            }
            catch (Exception)
            {
                return RedirectToAction("Delete", new { id = id, saveChangesError = true });
            }

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

src/ContosoUniversity.Website/Views/Shared/_Layout.cshtml
@inject IOptions<AppSettings> AppSettings
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - ContosoUniversity.Website</title>

        <environment names="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment names="Staging,Production">
            <link rel="stylesheet" href="//ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/css/bootstrap.min.css"
                  asp-fallback-test-class="hidden" asp-fallback-test-property="visibility" asp-fallback-test-value="hidden" />
            <link rel="stylesheet" href="~/css/site.css" asp-file-version="true" />
        </environment>
    </head>
    <body>
        <github-forkme repository="@AppSettings.Value.Repository" />
        @await Html.PartialAsync("_Navigation", AppSettings.Value.SiteTitle)
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.UtcNow.Year - <a href="http://github.com/@AppSettings.Value.Repository">@AppSettings.Value.SiteTitle</a></p>
            </footer>
        </div>

        <environment names="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/lib/hammer.js/hammer.js"></script>
            <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
            <script src="~/js/site.js"></script>
        </environment>
        <environment names="Staging,Production">
            <script src="//ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery">
            </script>
            <script src="//ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
            </script>
            <script src="//ajax.aspnetcdn.com/ajax/hammer.js/2.0.4/hammer.min.js"
                    asp-fallback-src="~/lib/hammer.js/hammer.js"
                    asp-fallback-test="window.Hammer">
            </script>
            <script src="~/js/site.js" asp-file-version="true"></script>
        </environment>

        @RenderSection("scripts", required: false)
    </body>
</html>

src/ContosoUniversity.Website/Views/Shared/_Navigation.cshtml
@model string

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a asp-controller="Home" asp-action="Index" class="navbar-brand">@Model</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                <li><a asp-controller="Home" asp-action="About">About</a></li>
                <li><a asp-controller="Student" asp-action="Index">Students</a></li>

                <li class="dropdown">
                    <a href="#" data-toggle="dropdown" class="dropdown-toggle">Course <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a asp-controller="Course" asp-action="Index">Courses</a></li>
                        <li><a asp-controller="Course" asp-action="UpdateCourseCredits">Update Credits</a></li>
                    </ul>
                </li>

                <li><a asp-controller="Instructor" asp-action="Index">Instructors</a></li>
                <li><a asp-controller="Department" asp-action="Index">Departments</a></li>
            </ul>
        </div>
    </div>
</div>